### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by lozalojo**
Added Spanish translation

### CODE REVIEW

**Comment by Feu-Secret** [comment]
Hey @lozalojo ! Thank you ! I will merge the PR into the dev branch.

**Comment by lozalojo** [comment]
Great, thank you!

**Review by Feu-Secret — APPROVED** [review]

**Comment by Feu-Secret** [comment]
Hey @lozalojo, have you a discord avatar?

**Comment by lozalojo** [comment]
Yes, Viriato139ac#0342

**Pull request merged**
